name: roman-numerals
version: 1.2.0.6

dependencies:
  - base

default-extensions:
  - GHC2021
  - LambdaCase

library:
  exposed-modules: Roman
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - roman-numerals
      - hspec
